### ISSUE TITLE
Несколько багов с переводами

### ISSUE THREAD

**Issue by skepsys** [StepicOrg/stepik-i18n#20]
@nag5000 Заметили, несколько косяков с переводами.

1. Не все переведено (см. скриншот).
![image](https://user-images.githubusercontent.com/1492370/96713862-fb36b780-13a9-11eb-8cd5-a7b5f0556421.png)

Посмотрел айдишники строк через `i18nDebugKeys()`, но в текущей репе таких не нашел (напр. `catalog.search-bar.with-cert-only`). Подозреваю, русская/английская версии, с которой мы переводили не самая последняя. Можно ли ее обновить в репе? Или как лучше поступить, чтобы обновить перевод?

2. Область 2 на скриншоте вообще не переводится? Есть английская и русская версия, но нет айдишников.

3. Белорусский и испанский языки с маленькой буквы при выборе в меню, остальные с большой. Но списки тоже не в репе. Как можно поправить?

**Comment by skepsys** [comment]
К пункту 1. Еще несколько мест с новой страніцы каталога, где нет строк в репе:

![image](https://user-images.githubusercontent.com/1492370/96714693-31286b80-13ab-11eb-8fb3-ce0adf4d28d2.png)

![image](https://user-images.githubusercontent.com/1492370/96714674-2a015d80-13ab-11eb-91e6-37485f66093c.png)

![image](https://user-images.githubusercontent.com/1492370/96714765-5026fd80-13ab-11eb-891a-1225c10d8e61.png)

**Comment by nag5000** [comment]
Привет!

1. Прошу прощения, но переводы в этом репозитории не обновляются автоматически. Я обновил на свежие.
2. Область 2 не переводится. Эти категории задаются и формируются нами. На данный момент есть две версии нового каталога - Ru и En (относительно контента, а не локализации). Какой каталог отображается - зависит от языка профиля пользователя или от текущего языка браузера, если пользователь - гость. Для украинского и белорусского языков отображается русский каталог. Для всех остальных - английский.
3. Спасибо, что заметили это! Исправим (примерно со след. недели).
