### ISSUE TITLE
Some translation keys missing on pt.yml file

### ISSUE THREAD

**Issue by mayconmk** [StepicOrg/stepik-i18n#23]
Dear Aleksey;

    Recently I noticed that some translation keys are missing at the translation file (pt.yml) of Portuguese language:

![exp1](https://user-images.githubusercontent.com/31141994/102607728-8b258300-4107-11eb-8595-febe168b555d.PNG)
![exp2](https://user-images.githubusercontent.com/31141994/102607742-924c9100-4107-11eb-90d6-2cf851e9f89f.PNG)

    I listed below some of them (I figure out using the i18nDebugKeys() function on console mode):

**page 1:**
https://stepik.org/course/71802/syllabus?auth=login

>>missing translation keys:
syllabus.deadlines.open-since
syllabus.deadlines.hard-soft.part1
syllabus.deadlines.hard-soft.part2

**page 2:**
https://stepik.org/lesson/352816/step/1?unit=336782

>>missing translation keys:
quiz.passed_by
quiz.correct_ratio

    Note that on "page 2" the tags "Sample Input:" and "Sample Output:" have no translation key linked to them.

    What I need to do to translate them? Should I create a new translation key on pt.yml file?

**Comment by mayconmk** [comment]
The same issue you can see in this case (after submitting an exercise).
You can see tha have some tags that are still in english and don't have translation key linked to them:

![exp3](https://user-images.githubusercontent.com/31141994/102618097-ef9d0e00-4118-11eb-8373-e4194752887e.PNG)

**Comment by nag5000** [comment]
Hello @mayconmk!

> missing translation keys:
> syllabus.deadlines.open-since
> syllabus.deadlines.hard-soft.part1
> syllabus.deadlines.hard-soft.part2
> quiz.passed_by
> quiz.correct_ratio

Yeah, they are missing from the `pt.yml`. You can add these translations and open a new PR. Or you can suggest translations through our [support](https://support.stepik.org/).

Also note that the README.md has instructions on how to find all missing translations in a specific locale relative to en/ru.
Please let me know if you have any questions.

> Note that on "page 2" the tags "Sample Input:" and "Sample Output:" have no translation key linked to them.

> The same issue you can see in this case (after submitting an exercise).
You can see tha have some tags that are still in english and don't have translation key linked to them:

These texts are hardcoded in our codebase in english and have no translation keys. Actually, if you want, we can fix it (and provide translation keys for these texts), but it will probably be the end of January 2021.

**Comment by mayconmk** [comment]
Hi Aleksey! Thank you for your tips... I really appreciate it!

About missing translation keys, I'll make new suggestion for these tags as soon as I translate it. I'll let you know.

Now, About the harcored texts in English, can you please put in your tasks the possibility to translate them? No problem about ableing them only at the end of January 2021. Just let me know when they are abled to be translated and I'll do it. (Thank you about that... some students here in Brazil don't have access to learn English and nisunderstanding the language increase the their difficulties while learning programming tasks when they find some compilation errors.

**Comment by mayconmk** [comment]
Hello Aleksey!

    Are the hardcored texts in English enabled to be translated?

**Comment by nag5000** [comment]
Hello, thanks for the ping!

I just updated translations here in the repo. "Sample Input" and "Sample Output" can be translated now in `pt.yml` file. 

But I apologize, we cannot yet provide the ability to translate the code quiz output. We will let you know when it becomes possible.
