### ISSUE TITLE
Date format while editing Syllabus

### ISSUE THREAD

**Issue by mayconmk** [StepicOrg/stepik-i18n#24]
Hi Aleksey;

I also noticed that when we are editing the Syllabus, the date/time format is different os what we adopt here in Brazil... Is it possible to setup this feature, or maybe change the format when the user setup the language?

Current date/time format on Syllabus editing: month/day/year

Date/time format adopted in Brazil: day/month/year

![image](https://user-images.githubusercontent.com/31141994/103027646-02f31380-4535-11eb-90e5-9af92b2980a5.png)

**Comment by mayconmk** [comment]
Here in Brazil we also adopt the time format in 24 hours (0:00-23:59)... We do not use 1-12 AM and 1-12PM.
If possible, this feature could be set too, but the most important and that is causing confusion currently is the date format.

**Comment by nag5000** [comment]
Hello Maycon,

Thank you for pointing this out! We will fix it for the `pt` locale: `24/12/2020 16:00`.

**Comment by nag5000** [comment]
It should be fixed now. Please feel free to re-open if it's not.
