### ISSUE TITLE
Перевод на украинский

### ISSUE THREAD

**Issue by zimorodokan** [StepicOrg/stepik-i18n#5]
@nag5000 @taery @vyahhi Прошу описать поточные планы по локализации, чтобы не тратить зря время на переводы, которые вы не принимаете к использованию (я, Андрій Красоткін — автор существующего украинского перевода, создавал два пул реквеста к русскому и украинскому языкам).
Я хочу наличия у стэпика  полноценного украинского интерфейса, в том числе для того, чтобы запустить там курс на украинском языке (если команда стэпика в этом заинтересованна).
Во время предыдущих переводов были определённые неудобства, связанные с добавлением вами строк в русскую версию. Для того, чтобы отслеживать изменения, приходилось построчно сравнивать файлы переводов на наличие соответствующих ключей, которые в русской версии не отсортированы по алфавиту, что не добавляло удобства, как и отсутствие завершающей запятой. Если вы при добавлении новых ключей (и/или значений) будете формировать автоматически новые файлы переводов со стандартным русским (для украинского) или английским значением для непереведённого значения ключа, это упростит работу по переводу.

**Comment by nag5000** [comment]
@zimorodokan Спасибо за напоминание! 
На самом деле я держу в уме твою просьбу уже в течение двух недель :). Ориентировочно в этом месяце мы планируем изменить систему переводов, и ближе к релизу, когда всё станет более-менее понятно, я обязательно отпишусь, что изменится. Просим прощения за задержку с ответом, я надеялся отписаться по-раньше, но планы сдигаются, так что - примерно Февраль.

И спасибо за обратную связь, мы постараемся учесть перечисленные неудобства.

**Comment by nag5000** [comment]
Формат переводов изменился с JSON на YAML.
Стандарт, используемый для переводов - ICU Message Format: https://formatjs.io/guides/message-syntax, http://userguide.icu-project.org/formatparse/messages.
Ключи теперь отсортированы по алфавиту.
Недостающие ключи переводов теперь можно определить, см. README.md.

**Comment by nag5000** [comment]
@zimorodokan Привет! Лучше подождать, я обновлю в ближайшее время.

**Comment by nag5000** [comment]
@zimorodokan Обновил.

**Comment by zimorodokan** [comment]
@nag5000 Привет! Добавь, пожалуйста.
